### ISSUE TITLE
Error for input data: index 22 is out of bounds for axis 0 with size 22

### ISSUE THREAD

**Issue by xiaoguo1995** [mirzaevinom/prostate_segmentation#2]
Hi Inom,

I read your this tutorial and it looks like more efficient.

I put data folders as you mentioned on homepage and it throws an error:
**

> IndexError: index 22 is out of bounds for axis 0 with size 22

**
```
Dimension mismatch for ProstateDx-01-0055 in folder train
96 96

Traceback (most recent call last):
  File "train.py", line 190, in <module>
    n_imgs=15*10**4, batch_size=32)
  File "train.py", line 124, in keras_fit_generator
    dicom_to_array(img_rows, img_cols)
  File "train.py", line 66, in dicom_to_array
    imgs[int(filename[:-4])] = img
IndexError: index 22 is out of bounds for axis 0 with size 22
```

does it results from the data read?

I try int(filename[:-4] in both python 2 and python 3 and cannot figure out what does it mean here. 

I guess this error results from here?

Another problem is that I put all .dcm files for every patient. I'm not sure whether just only 1 .dcm for patient is used in this tutorial.

I also tried put only 1 .dcm file with each patient, but it throws much more error:

```
Dimension mismatch for ProstateDx-01-0042 in folder train
Dimension mismatch for ProstateDx-01-0023 in folder train
Dimension mismatch for Prostate3T-01-0003 in folder train
Dimension mismatch for Prostate3T-01-0006 in folder train
Dimension mismatch for Prostate3T-01-0015 in folder train
Dimension mismatch for Prostate3T-01-0005 in folder train
Dimension mismatch for Prostate3T-01-0004 in folder train
Dimension mismatch for ProstateDx-01-0043 in folder train
Dimension mismatch for Prostate3T-01-0010 in folder train
Dimension mismatch for ProstateDx-01-0019 in folder train
Dimension mismatch for Prostate3T-01-0026 in folder train
Dimension mismatch for ProstateDx-01-0006 in folder train
Dimension mismatch for ProstateDx-01-0005 in folder train
Dimension mismatch for ProstateDx-01-0044 in folder train
Dimension mismatch for ProstateDx-01-0011 in folder train
Dimension mismatch for Prostate3T-01-0001 in folder train
Dimension mismatch for Prostate3T-01-0025 in folder train
Dimension mismatch for ProstateDx-01-0054 in folder train
Dimension mismatch for Prostate3T-01-0019 in folder train
Dimension mismatch for Prostate3T-01-0020 in folder train
Dimension mismatch for ProstateDx-01-0060 in folder train
Dimension mismatch for ProstateDx-01-0076 in folder train
Dimension mismatch for ProstateDx-01-0001 in folder train
Dimension mismatch for Prostate3T-01-0030 in folder train
Dimension mismatch for Prostate3T-01-0028 in folder train
Dimension mismatch for ProstateDx-01-0073 in folder train
Dimension mismatch for Prostate3T-01-0024 in folder train
Dimension mismatch for ProstateDx-01-0014 in folder train
Dimension mismatch for Prostate3T-01-0008 in folder train
Dimension mismatch for Prostate3T-01-0016 in folder train
Dimension mismatch for ProstateDx-01-0063 in folder train
Dimension mismatch for ProstateDx-01-0055 in folder train
Dimension mismatch for ProstateDx-01-0038 in folder train
Dimension mismatch for ProstateDx-01-0052 in folder train
Dimension mismatch for Prostate3T-01-0017 in folder train
Dimension mismatch for ProstateDx-01-0035 in folder train
Dimension mismatch for ProstateDx-01-0082 in folder train
Dimension mismatch for Prostate3T-01-0014 in folder train
Dimension mismatch for ProstateDx-01-0071 in folder train
Dimension mismatch for ProstateDx-01-0058 in folder train
Dimension mismatch for ProstateDx-01-0075 in folder train
Dimension mismatch for ProstateDx-01-0021 in folder train
Dimension mismatch for Prostate3T-01-0002 in folder train
Dimension mismatch for ProstateDx-01-0080 in folder train
Dimension mismatch for ProstateDx-01-0028 in folder train
Dimension mismatch for ProstateDx-01-0074 in folder train
Dimension mismatch for ProstateDx-01-0056 in folder train
Dimension mismatch for ProstateDx-01-0059 in folder train
Dimension mismatch for Prostate3T-01-0022 in folder train
Dimension mismatch for Prostate3T-01-0021 in folder train
Dimension mismatch for Prostate3T-01-0013 in folder train
Dimension mismatch for Prostate3T-01-0009 in folder train
Dimension mismatch for Prostate3T-01-0007 in folder train
Dimension mismatch for Prostate3T-01-0029 in folder train
Dimension mismatch for ProstateDx-01-0013 in folder train
Dimension mismatch for Prostate3T-01-0023 in folder train
Dimension mismatch for Prostate3T-01-0018 in folder train
Dimension mismatch for Prostate3T-01-0012 in folder train
Dimension mismatch for Prostate3T-01-0027 in folder train
Dimension mismatch for Prostate3T-01-0011 in folder train
Traceback (most recent call last):
  File "train.py", line 190, in <module>
    n_imgs=15*10**4, batch_size=32)
  File "train.py", line 124, in keras_fit_generator
    dicom_to_array(img_rows, img_cols)
  File "train.py", line 93, in dicom_to_array
    imgs = np.concatenate(imgs, axis=0).reshape(-1, img_rows, img_cols, 1)
ValueError: need at least one array to concatenate

```

I guess all .dcm files are needed and the error results from numpy array shape when reading images, but feel puzzled on it.

Could you please give some advice?

Thank you very much!

Best,
Peter

**Comment by mirzaevinom** [comment]
Hi Peter,

   I never had this issue so I can't really tell you what is going wrong. This might be because of your modifications to the codes.

Regards,
Inom

**Comment by xiaoguo1995** [comment]
Hi Inom,

I find the possible problem.

It results from the difference between python 2 and python 3:

```
        for dirName, subdirList, fileList in os.walk(PathDicom):

            if any(".dcm" in s for s in fileList):
                ptn_name = dirName.split('/')[3]
                fileList = list(filter(lambda x: '.dcm' in x, fileList))
                indice = [ int( fname[:-4] ) for fname in fileList]
                imgs = np.zeros( [indice[-1]+1, img_rows, img_cols])
```

indice[-1] + 1 is the problem.
`
this problem resembles the below problem "i += 1":

```
z = np.range(1000)

for i in z:
    while True:
    H_2 = 0.58*e(-(z[i]/81)**2)
    i += 1
```

Thank you very much! will try to figure how to fix it.

Best,
Peter

**Comment by xiaoguo1995** [comment]
Hi Inom,

Problem is fixed.

Adding `indice.sort()` after` indice = [ int( fname[:-4] ) for fname in fileList]`  solves this problem.

Best,
Peter

**Comment by mirzaevinom** [comment]
Hi Peter,
  Sorry for the late reply. I was out of traveling last week. I am glad that you got the code working on Python 3.

Regards,
Inom
